# Generated by Django 3.2.9 on 2021-11-30 18:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[accounts.models.phone_validator]),
        ),
    ]
