# Generated by Django 3.2.9 on 2021-12-06 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=400)),
                ('total_target', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('donation', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('raters', models.IntegerField(default=0)),
                ('avg_rate', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
                ('featured', models.BooleanField(default=False, null=True)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_report', models.CharField(max_length=400)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_report', models.CharField(max_length=400)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComments',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=400)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.projectscategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='addproject.Tags'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_featured', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_project', to='addproject.project')),
            ],
        ),
    ]
