# Generated by Django 3.2.9 on 2021-11-30 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=400)),
                ('total_target', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('donation', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('raters', models.IntegerField(default=0)),
                ('avg_rate', models.FloatField(default=0)),
                ('tags', models.CharField(blank=True, choices=[('tag1', 'tag1'), ('tag2', 'tag2'), ('tag3', 'tag3'), ('tag4', 'tag4'), ('tag5', 'tag5'), ('tag6', 'tag6')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_report', models.CharField(max_length=400)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_report', models.CharField(max_length=400)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComments',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=400)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addproject.project')),
            ],
        ),
    ]
