# Generated by Django 3.2.9 on 2021-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_pro', models.CharField(max_length=20)),
            ],
        ),
    ]
