# Generated by Django 3.2.9 on 2021-12-04 18:30

import addproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0003_alter_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=addproject.models.image_upload),
        ),
        migrations.AlterField(
            model_name='projectpics',
            name='pic',
            field=models.ImageField(upload_to=addproject.models.image_upload),
        ),
    ]
