# Generated by Django 3.2.9 on 2021-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0004_auto_20211204_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectsTags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='addproject.Tags'),
        ),
    ]
