# Generated by Django 3.2.9 on 2021-12-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0006_project_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
