# Generated by Django 3.2.9 on 2021-12-05 16:35

import addproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0007_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=addproject.models.image_upload),
        ),
    ]
