# Generated by Django 3.2.9 on 2021-12-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0008_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectscategory',
            name='categories',
        ),
        migrations.AddField(
            model_name='projectscategory',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
