# Generated by Django 3.2.9 on 2021-12-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0008_categories'),
        ('addproject', '0008_project_created_at'),
    ]

    operations = [
    ]
